{"name": "test_chunks_per_source_out_of_range_raises_error[4]", "status": "skipped", "statusDetails": {"message": "XFAIL Docs say chunks_per_source <= 3, backend allows 4.\n\nFailed: DID NOT RAISE <class 'requests.exceptions.HTTPError'>", "trace": "cps = 4\n\n    @pytest.mark.negative\n    @pytest.mark.xfail(reason=\"Docs say chunks_per_source <= 3, backend allows 4.\")\n    @pytest.mark.parametrize(\"cps\", [0,4])\n    @allure.severity(allure.severity_level.CRITICAL)\n    def test_chunks_per_source_out_of_range_raises_error(cps):\n        payload = {\n            \"query\": \"History of the FIFA World Cup\",\n            \"search_depth\": \"advanced\",\n            \"chunks_per_source\": cps\n        }\n>       assert_tavily_exception_error(payload,exception_messages[\"invalidChunksRange\"], requests.exceptions.HTTPError)\n\ntest_tavily_api.py:438: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ \n\npayload = {'chunks_per_source': 4, 'query': 'History of the FIFA World Cup', 'search_depth': 'advanced'}\nexpected_error_msg = '422 Client Error: Unprocessable Entity for url: https://api.tavily.com/search', exception_name = <class 'requests.exceptions.HTTPError'>\n\n    def assert_tavily_exception_error(payload, expected_error_msg,exception_name: Type[BaseException] = BadRequestError):\n>           with pytest.raises(exception_name) as exc:\nE           Failed: DID NOT RAISE <class 'requests.exceptions.HTTPError'>\n\ntest_tavily_api.py:701: Failed"}, "parameters": [{"name": "cps", "value": "4"}], "start": 1754785412843, "stop": 1754785416375, "uuid": "a1ccab06-aa61-4b93-a771-d0091d1425a1", "historyId": "d4dce08ecd47b855e38e29470dba94ec", "testCaseId": "912a981511b1e56aba6f0993ba7292bf", "fullName": "test_tavily_api#test_chunks_per_source_out_of_range_raises_error", "labels": [{"name": "epic", "value": "Tavily Search API"}, {"name": "severity", "value": "critical"}, {"name": "tag", "value": "@pytest.mark.xfail(reason='Docs say chunks_per_source <= 3, backend allows 4.')"}, {"name": "tag", "value": "negative"}, {"name": "suite", "value": "test_tavily_api"}, {"name": "host", "value": "DESKTOP-FTL2TTS"}, {"name": "thread", "value": "16220-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_tavily_api"}], "links": [{"type": "link", "url": "https://docs.tavily.com/documentation/api-reference/endpoint/search", "name": "API Reference"}]}